services:
  # Set up my-app
  app:
    build: .
    image: 01barthez/iphone-cameroon
    container_name: resto
    ports:
      - '10000:10000'
    secrets:
      - app_env
    volumes:
      - ./:/app
      - ./logs:/app/logs
    command: ['yarn', 'start']

  # Set up nginx service as reverse proxyversion: '3.8'

  client:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`client.foodi.infy.uk`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
    networks:
      - traefik-public

secrets:
  app_env:
    file: .env


networks:
  traefik-public:
    external: true
