services:
  # Set up my-app
  app:
    build: .
    image: 01barthez/iphone-cameroon
    container_name: resto
    ports:
      - '10000:10000'
    secrets:
      - app_env
    volumes:
      - ./:/app
      - ./logs:/app/logs
    networks:
      - iphone-cameroon
    command: ['yarn', 'start']

  # Set up nginx service as reverse proxy
  nginx:
    image: nginx:1.27.2-alpine-slim
    restart: always
    container_name: iphone-cameroon-nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    
    secrets:
      - app_env
    networks:
      - iphone-cameroon
    depends_on:
      - app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 20s
      timeout: 10s
      retries: 3

secrets:
  app_env:
    file: .env

volumes:
  nginx-config:

networks:
  iphone-cameroon:
    driver: bridge
