FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

# Installer les dépendances
RUN yarn install --frozen-lockfile

COPY . .


# Compiler le code TypeScript (si nécessaire)
RUN yarn build

EXPOSE 4000


# Commande pour démarrer l'application
CMD ["node", "dist/app.js"]