# Utiliser une image de base Python
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers nécessaires dans le conteneur
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port 8000 pour Django
EXPOSE 8000

# Commande par défaut pour lancer Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]