
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./programme:/app
    ports:
      - "8000:8000"
    depends_on:
      - rasa
    environment:
      - RASA_URL=http://rasa:5005/webhooks/rest/webhook

  rasa:
    image: rasa/rasa:latest-full
    volumes:
      - ./rasa:/app
    ports:
      - "5005:5005"
    command: run --enable-api