name: 'Create Tag'
description: 'Creates a new git tag for the release version'
inputs:
  GH_PAT:
    description: 'Define the GitHub Personal Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure Git user
      run: |
        git config --global user.email "${{ github.event.pusher.email || 'cesaristos5@gmail.com' }}"
        git config --global user.name "${{ github.actor }}"
      shell: bash

    - name: Bump version and create changelog
      run: npx standard-version
      shell: bash

    - name: Validate version format and create tag
      run: |
        VERSION=$(node -p "require('./package.json').version")
        TAG="v$VERSION"

        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG already exists, skipping tag creation."
        else
          git tag -a "$TAG" -m "Release version $TAG"
          echo "Tag $TAG created."
        fi
      shell: bash

    - name: Fetch all tags
      run: git fetch --tags
      shell: bash

    - name: Push tags to GitHub
      run: |
        VERSION=$(node -p "require('./package.json').version")
        TAG="v$VERSION"

        if [ -n "$TAG" ]; then
          git remote set-url origin https://x-access-token:${{ inputs.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin "$TAG"
        else
          echo "Tag is empty, skipping push."
        fi
      shell: bash
