entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false  # Désactive l'exposition automatique des services Docker

api:
  dashboard: true  # Active le dashboard Traefik

certificatesResolvers:
  letsencrypt:
    acme:
      email: "cesaristos5@gmail.com"  # Remplace par ton email
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {}