name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client Image
        run: |
          docker build -t your-dockerhub-username/client ./client
          docker push your-dockerhub-username/client

      - name: Build and Push Manager Image
        run: |
          docker build -t your-dockerhub-username/manager ./server/manager
          docker push your-dockerhub-username/manager

      - name: Build and Push Programme Image
        run: |
          docker build -t your-dockerhub-username/programme ./server/programme
          docker push your-dockerhub-username/programme

      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@<SERVER_IP> "
            cd /path/to/your/project &&
            docker-compose pull &&
            docker-compose up -d"